name: Run Tests

on:
  push:
    branches: [ main ]  # Or any other branches you want to trigger the workflow
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
      - name: Run Tests
        run: |
          python -m unittest tests/test_utils.py
